### PR TITLE
added data binding support

### PR DESCRIPTION
**Pull request by CleverChuk**
Added data binding support to avoid the expensive id look up using findViewBy

### CODE REVIEW

**Comment by emmaunel** [comment]
So with the binding support, you don't have manually bind it like this,
EditText name = (EditText) findViewById(R.id.edt); ?

**Comment by MaherSoua** [comment]
Very interesting, to avoid confusion with the other library Butter Knife we can keep them both , we will use Butter Knife to bind handler with view if you want.

**Comment by Madonahs** [comment]
We can try to fix this. 😊. I will look into Butter knife.

**Comment by CleverChuk** [comment]
I think DataBinding support library is cleaner and we can you use it to bind data to UI as well. It is up to you guys though but I prefer we stick with core android libs as possible 😃

**Comment by MaherSoua** [comment]
I agree the case that we may use it like click handler something like that 
@OnClick(R.id.button_name) public void anyAction() {} 
Take a look at its documentation and you can see where and when we can use it
http://jakewharton.github.io/butterknife/

**Comment by Madonahs** [comment]
Can you look at master,  I noticed some couple of errors. Not yet good with
binding. 😀 we can try to fix this.

**Comment by CleverChuk** [comment]
Sure

**Comment by Madonahs** [comment]
@ch thanks @MaherSoua Looks interesting.

**Comment by CleverChuk** [comment]
* Resolving the conflicts between my pull request and emmaunels
* Adding Databinding support to onboarding activity

**Pull request merged**
