### PR TITLE
Change package name, fix bug when text input are empty

### LINKED ISSUE #42: Reset password
when user forget password we have to add link or button to help him recover it.

### PR DESCRIPTION
**Pull request by MaherSoua**
this fixes #42

### CODE REVIEW

**Comment by Madonahs** [comment]
I can see, how about register?

**Comment by MaherSoua** [comment]
oops, I just fixed too.

**Comment by Madonahs** [comment]
Thanks  👍

**Comment by Madonahs** [comment]
Hey @MaherSoua  I think look at this line , 
```
remote: Counting objects: 31, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 31 (delta 11), reused 27 (delta 10), pack-reused 0
Unpacking objects: 100% (31/31), done.
From https://github.com/Madonahs/GrowWithGoogleTeamProject
   7645533..af9a755  develop             -> origin/develop
 * [new branch]      firebase-connection -> origin/firebase-connection
Updating 2cf2c16..af9a755
Fast-forward
 app/google-services.json                           | 55 ----------------------
 .../{database => login}/AppLoginManager.java       |  3 +-
 .../ui/LoginActivity.java                          |  2 +-
 .../ui/fragment/LoginFragment.java                 | 13 ++---
```
The removal of json will surely make anyone not access the branch 👍  we can try gitignore, we can have a nice session on gitignore 👍 .

**Pull request merged**
