### PR TITLE
Applying Butter Knife in some class

### PR DESCRIPTION
**Pull request by MaherSoua**

### CODE REVIEW

**Comment by Madonahs** [comment]
I am really happy to learn this, when ready let us know and i will pull.

**Comment by MaherSoua** [comment]
@Madonahs merged on master :D you can pull

**Comment by MaherSoua** [comment]
I just remember another library which may helps us if we want to load Image from network, it is ImageLoader when we will have this case we will add it.

**Comment by Madonahs** [comment]
@MaherSoua  This is awesome.

**Pull request merged**
