### PR TITLE
Login register activities

### PR DESCRIPTION
**Pull request by emmaunel**

### CODE REVIEW

**Comment by Madonahs** [comment]
Did you check my Inputs? I fixed the issues.

**Comment by Madonahs** [comment]
Great @rssinghji nice job.

**Comment by MaherSoua** [comment]
Hi all I added a class that will helps us to manage ViewPager, sorry I didn't create a PR for that because I don't know how to do it in github, the commit is added to the branch login-register-activity.

**Comment by Madonahs** [comment]
@MaherSoua  💯 👍

**Pull request merged**
