### PR TITLE
Profile activity

### PR DESCRIPTION
**Pull request by CleverChuk**
* The UI has been completed.
* Created a model

### CODE REVIEW

**Comment by Madonahs** [comment]
👍

**Comment by emmaunel** [comment]
Looking very good

**Comment by emmaunel** [comment]
I'm getting an error. In the ProfileFragment, android studio can't resolve 'FragmentProfileBinding'. Is this class that you forgot to add to git?

**Comment by Madonahs** [comment]
Did you try pulling master? Master runs fine. Git pull and let me know.

**Pull request merged**
